project:
  type: website
  output-dir: docs
 
website:
  title: "radiologie15"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: score_calcique_coronarien.qmd
        text: score calcique
      - href: coroscanner.qmd
        text: coroscanner
      - href: tavi/tavi_scanner.qmd
        text: Tavi
      
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Index"
        href: index.qmd
      - section: "About"
        contents:
          - introduction.qmd
          - about.qmd
      - section: "Scanner"
        contents:
          - score_calcique_coronarien.qmd
          - coroscanner.qmd
          - tavi/tavi_scanner.qmd
          
format:
  html:
    theme:
      - superhero
      - brand
    css: styles.css
    toc: true
    toc-title: "Sur cette page"
    page-layout: full
    lightbox: true



